// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15HM_Kh2OiF5U4_RZ2Co2AJDoXGCcw9c',
    appId: '1:745499890422:web:8bedb70b1b51afcad452d7',
    messagingSenderId: '745499890422',
    projectId: 'medease-39199',
    authDomain: 'medease-39199.firebaseapp.com',
    storageBucket: 'medease-39199.appspot.com',
    measurementId: 'G-B66M44NGWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHgCndP2DBqopckSncvRHdUl0vGszRG2w',
    appId: '1:745499890422:android:add2b0bee0205e46d452d7',
    messagingSenderId: '745499890422',
    projectId: 'medease-39199',
    storageBucket: 'medease-39199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_QW34PMSSGgySi42rdMIIROygprAsR64',
    appId: '1:745499890422:ios:977460498d88c3e0d452d7',
    messagingSenderId: '745499890422',
    projectId: 'medease-39199',
    storageBucket: 'medease-39199.appspot.com',
    iosBundleId: 'y',
  );

}